version: "3.9"

services:
    backend:
        # restart: always
        build:
            context: ./backend
            dockerfile: Dockerfile.dev
        container_name: backend
        volumes:
            - /app/node_modules
            - ./backend:/app
        # ports:
        #     - 5000:5000
        depends_on:
            - mongodb
        env_file:
            - .env
        environment:
            NODE_ENV: ${NODE_ENV}
            MONGO_URI: mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@mongodb
        networks:
            - api-services

    mongodb:
        image: mongo
        # restart: always
        ports:
            - 27017:27017
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
        volumes:
            - mongodb-data:/data/db
        networks:
            - api-services

    mongo-express:
        image: mongo-express
        depends_on:
            - mongodb
        ports:
            - 8081:8081
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USERNAME}
            ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWORD}
            ME_CONFIG_MONGODB_SERVER: mongodb
            ME_CONFIG_BASICAUTH_USERNAME: admin
            ME_CONFIG_BASICAUTH_PASSWORD: admin123456
        volumes:
            - mongodb-data
        networks:
            - api-services

    frontend:
        # resart: always
        build:
            context: ./frontend
            dockerfile: Dockerfile.dev
        environment:
            CHOKIDAR_USEPOLLING: 'true'
        container_name: frontend
        volumes:
            - ./app/node_modules
            - ./frontend:/app
        # ports: 
        #     - 3000:3000
        env_file:
            - .env
        depends_on: 
            - backend
        networks: 
            - api-services

    nginx:
        # restart: always
        depends_on:
            - backend
            - frontend
        build: 
            context: ./nginx
            dockerfile: Dockerfile.dev
        ports: 
            - 80:80
        networks: 
            - api-services

networks:
    api-services:
        driver: bridge

volumes:
    mongodb-data:
        driver: local
